/* 
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Aylien.NewsApi.Client.OpenAPIDateConverter;

namespace Aylien.NewsApi.Model
{
    /// <summary>
    /// Coverages
    /// </summary>
    [DataContract]
    public partial class Coverages :  IEquatable<Coverages>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Coverages" /> class.
        /// </summary>
        /// <param name="coverages">An array of coverages for the input story.</param>
        /// <param name="storyBody">The input story body.</param>
        /// <param name="storyLanguage">The input story language.</param>
        /// <param name="storyPublishedAt">The input story published date.</param>
        /// <param name="storyTitle">The input story title.</param>
        public Coverages(List<Story> coverages = default(List<Story>), string storyBody = default(string), string storyLanguage = default(string), DateTime storyPublishedAt = default(DateTime), string storyTitle = default(string))
        {
            this._Coverages = coverages;
            this.StoryBody = storyBody;
            this.StoryLanguage = storyLanguage;
            this.StoryPublishedAt = storyPublishedAt;
            this.StoryTitle = storyTitle;
        }
        
        /// <summary>
        /// An array of coverages for the input story
        /// </summary>
        /// <value>An array of coverages for the input story</value>
        [DataMember(Name="coverages", EmitDefaultValue=false)]
        public List<Story> _Coverages { get; set; }

        /// <summary>
        /// The input story body
        /// </summary>
        /// <value>The input story body</value>
        [DataMember(Name="story_body", EmitDefaultValue=false)]
        public string StoryBody { get; set; }

        /// <summary>
        /// The input story language
        /// </summary>
        /// <value>The input story language</value>
        [DataMember(Name="story_language", EmitDefaultValue=false)]
        public string StoryLanguage { get; set; }

        /// <summary>
        /// The input story published date
        /// </summary>
        /// <value>The input story published date</value>
        [DataMember(Name="story_published_at", EmitDefaultValue=false)]
        public DateTime StoryPublishedAt { get; set; }

        /// <summary>
        /// The input story title
        /// </summary>
        /// <value>The input story title</value>
        [DataMember(Name="story_title", EmitDefaultValue=false)]
        public string StoryTitle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Coverages {\n");
            sb.Append("  _Coverages: ").Append(_Coverages).Append("\n");
            sb.Append("  StoryBody: ").Append(StoryBody).Append("\n");
            sb.Append("  StoryLanguage: ").Append(StoryLanguage).Append("\n");
            sb.Append("  StoryPublishedAt: ").Append(StoryPublishedAt).Append("\n");
            sb.Append("  StoryTitle: ").Append(StoryTitle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Coverages);
        }

        /// <summary>
        /// Returns true if Coverages instances are equal
        /// </summary>
        /// <param name="input">Instance of Coverages to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Coverages input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Coverages == input._Coverages ||
                    this._Coverages != null &&
                    input._Coverages != null &&
                    this._Coverages.SequenceEqual(input._Coverages)
                ) && 
                (
                    this.StoryBody == input.StoryBody ||
                    (this.StoryBody != null &&
                    this.StoryBody.Equals(input.StoryBody))
                ) && 
                (
                    this.StoryLanguage == input.StoryLanguage ||
                    (this.StoryLanguage != null &&
                    this.StoryLanguage.Equals(input.StoryLanguage))
                ) && 
                (
                    this.StoryPublishedAt == input.StoryPublishedAt ||
                    (this.StoryPublishedAt != null &&
                    this.StoryPublishedAt.Equals(input.StoryPublishedAt))
                ) && 
                (
                    this.StoryTitle == input.StoryTitle ||
                    (this.StoryTitle != null &&
                    this.StoryTitle.Equals(input.StoryTitle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Coverages != null)
                    hashCode = hashCode * 59 + this._Coverages.GetHashCode();
                if (this.StoryBody != null)
                    hashCode = hashCode * 59 + this.StoryBody.GetHashCode();
                if (this.StoryLanguage != null)
                    hashCode = hashCode * 59 + this.StoryLanguage.GetHashCode();
                if (this.StoryPublishedAt != null)
                    hashCode = hashCode * 59 + this.StoryPublishedAt.GetHashCode();
                if (this.StoryTitle != null)
                    hashCode = hashCode * 59 + this.StoryTitle.GetHashCode();
                return hashCode;
            }
        }
    }

}
