/* 
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Aylien.NewsApi.Client.OpenAPIDateConverter;

namespace Aylien.NewsApi.Model
{
    /// <summary>
    /// EntityLinks
    /// </summary>
    [DataContract]
    public partial class EntityLinks :  IEquatable<EntityLinks>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntityLinks" /> class.
        /// </summary>
        /// <param name="dbpedia">A dbpedia resource URL.</param>
        public EntityLinks(string dbpedia = default(string))
        {
            this.Dbpedia = dbpedia;
        }
        
        /// <summary>
        /// A dbpedia resource URL
        /// </summary>
        /// <value>A dbpedia resource URL</value>
        [DataMember(Name="dbpedia", EmitDefaultValue=false)]
        public string Dbpedia { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EntityLinks {\n");
            sb.Append("  Dbpedia: ").Append(Dbpedia).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EntityLinks);
        }

        /// <summary>
        /// Returns true if EntityLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of EntityLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntityLinks input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Dbpedia == input.Dbpedia ||
                    (this.Dbpedia != null &&
                    this.Dbpedia.Equals(input.Dbpedia))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Dbpedia != null)
                    hashCode = hashCode * 59 + this.Dbpedia.GetHashCode();
                return hashCode;
            }
        }
    }

}
