/* 
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Aylien.NewsApi.Client.OpenAPIDateConverter;

namespace Aylien.NewsApi.Model
{
    /// <summary>
    /// The format of media
    /// </summary>
    /// <value>The format of media</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum MediaFormat
    {
        /// <summary>
        /// Enum BMP for value: BMP
        /// </summary>
        [EnumMember(Value = "BMP")]
        BMP = 1,

        /// <summary>
        /// Enum GIF for value: GIF
        /// </summary>
        [EnumMember(Value = "GIF")]
        GIF = 2,

        /// <summary>
        /// Enum JPEG for value: JPEG
        /// </summary>
        [EnumMember(Value = "JPEG")]
        JPEG = 3,

        /// <summary>
        /// Enum PNG for value: PNG
        /// </summary>
        [EnumMember(Value = "PNG")]
        PNG = 4,

        /// <summary>
        /// Enum TIFF for value: TIFF
        /// </summary>
        [EnumMember(Value = "TIFF")]
        TIFF = 5,

        /// <summary>
        /// Enum PSD for value: PSD
        /// </summary>
        [EnumMember(Value = "PSD")]
        PSD = 6,

        /// <summary>
        /// Enum ICO for value: ICO
        /// </summary>
        [EnumMember(Value = "ICO")]
        ICO = 7,

        /// <summary>
        /// Enum CUR for value: CUR
        /// </summary>
        [EnumMember(Value = "CUR")]
        CUR = 8,

        /// <summary>
        /// Enum WEBP for value: WEBP
        /// </summary>
        [EnumMember(Value = "WEBP")]
        WEBP = 9,

        /// <summary>
        /// Enum SVG for value: SVG
        /// </summary>
        [EnumMember(Value = "SVG")]
        SVG = 10

    }

}
