/* 
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Aylien.NewsApi.Client.OpenAPIDateConverter;

namespace Aylien.NewsApi.Model
{
    /// <summary>
    /// The type of media
    /// </summary>
    /// <value>The type of media</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum MediaType
    {
        /// <summary>
        /// Enum Image for value: image
        /// </summary>
        [EnumMember(Value = "image")]
        Image = 1,

        /// <summary>
        /// Enum Video for value: video
        /// </summary>
        [EnumMember(Value = "video")]
        Video = 2

    }

}
