/* 
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Aylien.NewsApi.Client.OpenAPIDateConverter;

namespace Aylien.NewsApi.Model
{
    /// <summary>
    /// Rankings
    /// </summary>
    [DataContract]
    public partial class Rankings :  IEquatable<Rankings>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rankings" /> class.
        /// </summary>
        /// <param name="alexa">alexa.</param>
        public Rankings(List<Rank> alexa = default(List<Rank>))
        {
            this.Alexa = alexa;
        }
        
        /// <summary>
        /// Gets or Sets Alexa
        /// </summary>
        [DataMember(Name="alexa", EmitDefaultValue=false)]
        public List<Rank> Alexa { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Rankings {\n");
            sb.Append("  Alexa: ").Append(Alexa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Rankings);
        }

        /// <summary>
        /// Returns true if Rankings instances are equal
        /// </summary>
        /// <param name="input">Instance of Rankings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Rankings input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Alexa == input.Alexa ||
                    this.Alexa != null &&
                    input.Alexa != null &&
                    this.Alexa.SequenceEqual(input.Alexa)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Alexa != null)
                    hashCode = hashCode * 59 + this.Alexa.GetHashCode();
                return hashCode;
            }
        }
    }

}
