/* 
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Aylien.NewsApi.Client.OpenAPIDateConverter;

namespace Aylien.NewsApi.Model
{
    /// <summary>
    /// The scope by level
    /// </summary>
    /// <value>The scope by level</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ScopeLevel
    {
        /// <summary>
        /// Enum International for value: international
        /// </summary>
        [EnumMember(Value = "international")]
        International = 1,

        /// <summary>
        /// Enum National for value: national
        /// </summary>
        [EnumMember(Value = "national")]
        National = 2,

        /// <summary>
        /// Enum Local for value: local
        /// </summary>
        [EnumMember(Value = "local")]
        Local = 3

    }

}
